# Pod example without Consul
apiVersion: v1
kind: Pod
metadata:
  name: counting-minimal-pod
  labels:
    app: counting-service
spec:
  containers:
    - name: counting-service
      image: hashicorp/counting-service:0.0.2
      ports:
      - containerPort: 9001
