---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-facebox
  labels:
    app: emojify-facebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-facebox
  template:
    metadata:
      labels:
        app: emojify-facebox
      annotations:
    spec:
      containers:
      - name: emojify-facebox
        image: "nicholasjackson/emojify-facedetection:v0.10.0"
        ports:
        - containerPort: 9090
        env:
        - name: MIN_NEIGHBORS
          value: "14"
        - name: SCALE_FACTOR
          value: "1.03"
        - name: STATSD_ADDRESS
          value: localhost:9125

      - name: prometheus-statsd
        image: "prom/statsd-exporter:latest"
        ports:
          - name: metrics
            containerPort: 9102
          - name: statsd
            containerPort: 9125
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
