apiVersion: v1
kind: Pod
metadata:
  name: counting-service-deployment
spec:
  containers:
  - name: counting-service
    image: hashicorp/counting-service:0.0.2
    ports:
    - containerPort: 9001
  - name: consul
    image: "consul:1.3.0"
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    command:
    - "/bin/sh"
    - "-ec"
    - |
      exec /bin/consul connect proxy \
            -http-addr=${HOST_IP}:8500 \
            -service=counting \
            -service-addr=127.0.0.1:9001 \
            -listen=${POD_IP}:19001 \
            -register
  initContainers:
  - name: counting-init
    image: hashicorp/counting-init:0.0.9
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
